v1.1.4 php 7 compatible
mtymek/MtMail pull request #33
Opened 2016-10-30 15:15 UTC by celtic34fr

just some correction about plugins declaration, but the same as my last version

2016-10-30 16:19 UTC, ojhaujjwal commented on README.md
> +It's a fork of mtymek/mt-mail package
seriously?

2016-10-30 16:23 UTC, mtymek requested changes
I added a few comments here and there regarding some details. However, what I'm missing is:
- some explanation in the PR: what are the new features and why you introduced them
- documentation in `doc` directory
- unit tests for new features

2016-10-30 16:23 UTC, mtymek commented on README.md
> -[![Total Downloads](https://poser.pugx.org/mtymek/mt-mail/downloads.png)](https://packagist.org/packages/mtymek/mt-mail)
Please revert this changes for the PR.

2016-10-30 16:23 UTC, mtymek commented on README.md
> +    'to' => 'johndoe@domain.com, Jade DOE<jade.doe@domain.net>',
Please revert to previous version.

2016-10-30 16:23 UTC, mtymek commented on composer.json
> +    "name": "celtic34fr/mt-mail",
Please revert to previous version

2016-10-30 16:23 UTC, mtymek commented on src/ComposerPlugin/EmbeddingImages.php
> + */
Remove auto-generated doc-block - it does not bring any useful information.

2016-10-30 16:24 UTC, ojhaujjwal commented on src/ComposerPlugin/PlaintextMessage.php
> +        /* suppression de la balise title */
only english please

2016-11-20 15:32 UTC, ojhaujjwal commented
Please add proper information in the PR description and the tests(mandatory). And some docs would be great as well.

2016-11-20 15:47 UTC, celtic34fr commented
my latest changes : 
remove the french comments
add some information about new plugin EmbeddingImages and how to declare multiple recipients for an email

for UnitTest i don't see how to set it to be efficient. For PlaintextMessage plugin, my changes affects the message rendered before creating the mail in text format. For EmbeddingImages plugin, the UnitTest is difficult to set up as i know. Could help me in that case ?

2018-03-15 14:11 UTC, celtic34fr commented
as I read, now MtMail is Php 7.2 compatible, this pulls request is full useless. I close it

2018-03-15 14:11 UTC, closed without merging